### ISSUE TITLE
挺好的但是因为JSON.stringify(option)也带来了些问题

### ISSUE THREAD

**Issue by JohnLou** [somonus/react-native-echarts#1]
挺好的，但是因为JSON.stringify(option)也带来了些问题。比如在option 里面有很多配置本身是支持函数的，比如 label 的 formatter，这边由于这个转化后，就会失效了。
另外可以支持theme不？

echarts有IOS和android的原生支持版本，可否基于哪个来实现下

**Comment by somonus** [comment]
确实有这个问题，我改改。
theme可以加上。

**Comment by somonus** [comment]
fixed
