### ISSUE TITLE
依赖的 echarts 版本有点旧

### ISSUE THREAD

**Issue by callcter** [somonus/react-native-echarts#102]
最新版本是 4.0.4
上次最新更新的版本是 3.7，支持图表中的富文本编辑，能更新一下吗

**Comment by DuanYuna** [comment]
我们也有同样的需求 更新依赖版本要怎么操作,您有空可以分享一下吗

**Comment by Anshiii** [comment]
查看一下源码 看到有一个文件是把 echart.js 源码变成字符串的，手动替换这份源码。

**Comment by DuanYuna** [comment]
是哪个文件方便说一下嘛

**Comment by Anshiii** [comment]
`...node_modules/native-echarts/src/components/Echarts/echarts.min.js`

**Comment by zhuxinleibandou** [comment]
> native

请问将哪份文件替换到tpl.html中？ 万分感谢～

**Comment by congshengwu** [comment]
同样的问题 #111

**Comment by callcter** [comment]
对于有大量图表及交互的场景下，这个WebView的实现方案不太适合，所以我们的项目老早就使用 https://github.com/wuxudong/react-native-charts-wrapper 了，其他对图标有需求的也可以看看这个组件
