### ISSUE TITLE
希望更新echarts到4.0版本

### ISSUE THREAD

**Issue by ahai3840** [somonus/react-native-echarts#111]

**Comment by personwu0755** [comment]
下载最新版本，覆盖tl.html中echarts代码就可

**Comment by zhuxinleibandou** [comment]
> 下载最新版本，覆盖tl.html中echarts代码就可

您好 请问在哪里下载最新的版本？

**Comment by congshengwu** [comment]
@zhuxinleibandou 
您好，到这里[https://github.com/apache/incubator-echarts/tree/4.9.0/dist](echarts 4.9.0)下载目前最新的4.9.0版本的echarts.js文件，复制里面全部的代码，覆盖到如下截图的位置，echarts就更新到最新版了。
![98badd05756f993529067fb69709d80](https://user-images.githubusercontent.com/26167428/94354131-c4bb9480-00aa-11eb-93cd-1f932ef28141.png)

**Comment by congshengwu** [comment]
@zhuxinleibandou
你好，到这里 https://github.com/apache/incubator-echarts/tree/4.9.0/dist 下载最新版本的echarts.js文件，复制文件里的全部代码，覆盖到本地tpl.html文件中的<script>覆盖这里</script>标签，即可更新。
