### ISSUE TITLE
debug正常，但是release还是不显示，我的rn是0.38

### ISSUE THREAD

**Issue by WhatAKitty** [somonus/react-native-echarts#12]

**Comment by WhatAKitty** [comment]
我把它升级成0.39，但是打包还是不行

**Comment by ztMalone** [comment]
真的感谢这个组件，但是release版本真机测试也是无法显示图标，react-native版本是0.34，急求修复

**Comment by somonus** [comment]
这是react-native的一个bug，解决方案参考facebook/react-native#6004

**Comment by 1610449813** [comment]
release版本只能使用uri加载资源，android把tpl.html文件放在android/app/src/main/assets文件里，使用uri:'file:///android_asset/tpl.html'这个地址加载，ios在项目目录下建个文件夹，把tpl文件放里面去，使用uri:'文件名/tpl'加载，这样能使用，但是好像无法使用webview和native见得通信

**Comment by 1610449813** [comment]
无法通信找到解决方法了，但是无法使用官方自己的webview，我使用react-native-webview-bridge这个，打包时忽略这个组建的webview方法就行了

**Comment by ztMalone** [comment]
@1610449813 这个问题解决了么，要我自己去改写这个组件么？

**Comment by 1610449813** [comment]
@ztMalone 恩，如果你不需要webview和native通信，可以使用原生的webview，把他组件里Echarts文件夹的index文件webview source路径改成我上面说的，要是需要通信的话，使用我上面说的第三方组件

**Comment by lin493369** [comment]
https://github.com/facebook/react-native/issues/505
参考 @1610449813 的答案。已解决！

**Comment by huzhiqi** [comment]
按照@1610449813 的方法还是没有解决

**Comment by Rylai-Zihang** [comment]
@1610449813  android release版本通过“把tpl.html文件放在android/app/src/main/assets文件里，使用uri:'file:///android_asset/tpl.html'这个地址加载”已解决！但是IOS下将tpl.html放在项目的一个新建文件夹下，在报URL was not found 的错误，大家都有遇到吗？

**Comment by belynnyond** [comment]
@Rylai-Zihang 大兄弟，你这个问题解决了么

**Comment by wangchongwei** [comment]
@1610449813 请问一下如何实现echarts和native的通信？
点击事件？要如何设置，在html中吗？

**Comment by ztMalone** [comment]
你可以查看百度echarts api 😊

From Todd Zhou's iPhone

**Comment by 1610449813** [comment]
看看echarts api，再看看react-native-webview-bridge就知道如何通信了，

**Comment by lsamio** [comment]
@1610449813 ios按上面解决方法 source={{uri:'app/tpl'}}显示URL was not found on this server 请问怎么解决

**Comment by gongchao** [comment]
@lsamio +1，请问这个问题解决了吗？

**Comment by ZhouYongfan** [comment]
npm install native-echarts --save之后一直下载不了，卡在loadRequestedDeps: still install loadDepsIntoIdealTree

**Comment by hanhui** [comment]
@1610449813 请问在您的android真机release版本的APK无法显示echarts图片的解决办法中，下面代码是修改的哪个地方的代码？
uri:'file:///android_asset/tpl.html'

**Comment by hanhui** [comment]
@1610449813 已解决，修改的是  \node_modules\native-echarts\src\components\Echarts\index.js中的代码，具体如下：
       源代码为：source={require('./tpl.html')}
       修改为：source={{uri:'file:///android_asset/tpl.html'}}

**Comment by linfeizhang** [comment]
我这边修改过代码后还是不显示啊！source={{uri:'file:///android_asset/tpl.html'}}，并且把tpl.html放到android/app/src/main/assets里了，但是还是不行啊，求解答啊！

**Comment by Hgq1001** [comment]
同路上一样  照着方法做了 饼图可以显示  仪表盘图可以显示 其他图就不行了  怎么解决啊 求大神指点

**Comment by will86** [comment]
@gongchao @lsamio @Rylai-Zihang @belynnyond  iOS的路径怎么放置，麻烦提示一下好吗，谢谢

**Comment by zhangyanf** [comment]
@will86 @Hgq1001  你们看看你们的代码，trigger: 'axis'，这个值是不是这个，不是的话改下，echart3.0，和echart2.0，有变化了，你们可以去官网查查代码，如果你们写的值是‘Time’的话，在Debug上可以显示，但是release上就显示不了了 ，

**Comment by zwyqz** [comment]
目前我的解决方法 
ios需要把tpl.html文件放到src/commonents/Echarts 里面
然后android 按照楼上的所说就行了

const source = (Platform.OS == 'ios') ? require('./tpl.html') : {'uri':'file:///android_asset/tpl.html'}
    console.log("source=",source);
    return (

      <View style={{flex: 1, height: this.props.height || 400,}}>
        <WebView
          ref="chart"
          scrollEnabled = {false}
          injectedJavaScript = {renderChart(this.props)}
          style={{
            height: this.props.height || 400,
          }}
          source={source}
        />
      </View>
    );

**Comment by zhangyanf** [comment]
你看看代码里的option，里边的trigger:的值是axis吗？

**Comment by zwyqz** [comment]
trigger: 'item',

**Comment by zhangyanf** [comment]
你好好看看echart 3.0 和echart 2.0 的option是不一样的

**Comment by gaozhaopei** [comment]
@zwyqz  我的柱状图 设置宽度不起作用  总是占据两个屏宽  有什么解决办法吗 谢谢

**Comment by simonguo** [comment]
@wangchongwei @1610449813  通讯可以使用 onMessage  

在` WebView `  上设置一个 onMessage ,  然后在 option 里面中的 function 中 可以通过 window.postMessage 传值。

**Comment by amijabd** [comment]
Please explain why need to modify:

Source = {require ('./tpl.html')} 

to

Modify Is: source = {{uri: 'file: ///android_asset/tpl.html'}}

**Comment by will86** [comment]
@amijabd 
The component WebView powered by Facebook requires that modify...

File of this path `./node_modules/native-echarts/src/components/Echarts/index.js` needs to be modified

**Comment by amijabd** [comment]
Yes, I made those changes based on the above by putting this:
source = {{uri: 'file: ///android_asset/tpl.html'}}

Still after I made a release, the charts still can't be viewed. Not sure what I'm doing wrong. Here's a page of one of my charts:

import React, { Component } from 'react';
import { Container, Header, Content, Card, CardItem, Text, Body, Left, Right, Button, H3 } from 'native-base';
import Echarts from 'native-echarts';

export default class SalesCategory extends Component {

  render() {
    const option = {
      title : {
          show: true,
          text: 'Sales by Category',
          subtext: 'Mar 24-Sept 30, 2016',
          x:'center'
      },
    tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b}: {c} ({d}%)"
    },
    legend: {
        show: false,
        orient: 'vertical',
        x: 'left',
        y: 'top',
        data:[
            '-',
            '1-Asian Food',
            '2-Chinese Food',
            '3-Western Food',
            '6-Retail',
            '7-Beverages',
            '8-Promotions',
            '9-Others',
            '-',
            '101-Rice',
            '102-Noodle',
            '103-Bread',
            '104-Snacks',
            '105-Dim Sum',
            '106-Value Set',
            '201-Fish',
            '202-Crab',
            '203-Prawn',
            '204-Meat',
            '301-Soup',
            '302-Salad',
            '303-Pasta',
            '304-Pizza',
            '305-Steak',
            '306-Burger',
            '601-Confectionary',
            '602-Retail Pack',
            '603-Groceries',
            '701-Hot Beverages',
            '702-Cold Beverages',
            '703-Can Beverages'
          ]
    },
    series: [
        {
            x: 'left',
            name:'Category',
            type:'pie',
            // selectedMode: 'single',
            radius: [0, '55%'],

            label: {
                normal: {
                    show: false,
                    position: 'inner'
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            data:[
              {name: "-", value: 17.62},
              {name: "1-Asian Food", value: 7479.39},
              {name: "2-Chinese Food", value: 2988.38},
              {name: "3-Western Food", value: 2586.36},
              {name: "6-Retail", value: 29900.57},
              {name: "7-Beverages", value: 13368.69},
              {name: "8-Promotions", value: 12180.91},
              {name: "9-Others", value: 136.76}
            ]
        },
        {
            name:'Category 2',
            type:'pie',
            radius: ['70%', '85%'],
            label: {
                normal: {
                    show: false,
                    formatter: '{a|{a}}{abg|}\n{hr|}\n  {b|{b}：}{c}  {per|{d}%}  ',
                    backgroundColor: '#eee',
                    borderColor: '#aaa',
                    borderWidth: 1,
                    borderRadius: 4,
                    rich: {
                        a: {
                            color: '#999',
                            lineHeight: 22,
                            align: 'center'
                        },
                        hr: {
                            borderColor: '#aaa',
                            width: '50%',
                            borderWidth: 0.5,
                            height: 0
                        },
                        b: {
                            fontSize: 16,
                            lineHeight: 33
                        },
                        per: {
                            color: '#eee',
                            backgroundColor: '#334455',
                            padding: [2, 4],
                            borderRadius: 2
                        }
                    }
                }
            },
            data:[
              {name: "-", name2: "-", value: 17.62},
              {name: "101-Rice", name2: "1-Asian Food", value: 4727.76},
              {name: "102-Noodle", name2: "1-Asian Food", value: 1434.98},
              {name: "103-Bread", name2: "1-Asian Food", value: 229.58},
              {name: "104-Snacks", name2: "1-Asian Food", value: 327.76},
              {name: "105-Dim Sum", name2: "1-Asian Food", value: 588.98},
              {name: "106-Value Set", name2: "1-Asian Food", value: 170.33},
              {name: "201-Fish", name2: "2-Chinese Food", value: 975.59},
              {name: "202-Crab", name2: "2-Chinese Food", value: 435.37},
              {name: "203-Prawn", name2: "2-Chinese Food", value: 386.43},
              {name: "204-Meat", name2: "2-Chinese Food", value: 862.97},
              {name: "205-Vegetable", name2: "2-Chinese Food", value: 328.02},
              {name: "301-Soup", name2: "3-Western Food", value: 618.41},
              {name: "302-Salad", name2: "3-Western Food", value: 265.55},
              {name: "303-Pasta", name2: "3-Western Food", value: 614.7},
              {name: "304-Pizza", name2: "3-Western Food", value: 454.71},
              {name: "305-Steak", name2: "3-Western Food", value: 325.73},
              {name: "306-Burger", name2: "3-Western Food", value: 307.26},
              {name: "601-Confectionery", name2: "6-Retail", value: 10220.11},
              {name: "602-Retail Pack", name2: "6-Retail", value: 18545.83},
              {name: "603-Groceries", name2: "6-Retail", value: 1134.63},
              {name: "701-Hot Beverages", name2: "7-Beverages", value: 7186.43},
              {name: "702-Cold Beverages", name2: "7-Beverages", value: 5542.38},
              {name: "703-Can Beverages", name2: "7-Beverages", value: 639.88},
              {name: "-", name2: "8-Promotions", value: 12180.91},
              {name: "-", name2: "9-Others", value: 136.76}
            ]
        }
    ]
};
    return (
      <Container>
        <Content padder>
          <Card>
            <CardItem>
                  <Button bordered small style={{marginRight: 10}}>
                    <Text>Category Lvl 2</Text>
                  </Button>
                  <Button bordered small>
                    <Text>Net Sales</Text>
                  </Button>
            </CardItem>
          </Card>
          <Card style={{height:450}}>
            <CardItem>
              <Body>
                <Echarts option={option} height={450} width={350} />
              </Body>
            </CardItem>
          </Card>
        </Content>
      </Container>
    );
  }
}

**Comment by amijabd** [comment]
Here's the page I did for one of the charts. Not sure where I'm going wrong.

```
import React, { Component } from 'react';
import { Container, Header, Content, Card, CardItem, Text, Body, Left, Right, Button, H3 } from 'native-base';
import Echarts from 'native-echarts';
export default class SalesProDepartment extends Component {
  render() {
    const option = {
    title : {
        show: true,
        text: 'Product Department',
        subtext: 'Mar 24-Sept 30, 2016',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient: 'horizontal',
        bottom: 'bottom',
        data: [
          "-",
          "F-F&B",
          "R-Retail"
        ]
    },
    series : [
        {
            name: 'Department',
            type: 'pie',
            xAxis: '',
            yAxis: '',
            radius: [0, '50%'],
            data:[
              {name: "-", value: 12198.53},
              {name: "F-F&B", value: 26559.58},
              {name: "R-Retail", value: 29900.57}
            ],
            itemStyle: {
                emphasis: {
                    shadowBlur: 10,
                    shadowOffsetX: 0,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]
};
    return (
      <Container>
        <Content padder>
          <Card>
            <CardItem>
              <Button bordered small style={{marginRight: 10}}>
                <Text>Department</Text>
              </Button>
              <Button bordered small>
                <Text>Net Sales</Text>
              </Button>
            </CardItem>
          </Card>
          <Card style={{height:450}}>
            <CardItem>
              <Body>
                <Echarts option={option} height={400} width={350} />
              </Body>
            </CardItem>
         </Card>
        </Content>
      </Container>
    );
  }
}
```

**Comment by will86** [comment]
@amijabd  
Confirm that, does the file `tpl.html` exists in the path `android/app/src/main/assets/tpl.html`?

**Comment by amijabd** [comment]
Nope. Its not there. I did the bundling but its not there.

**Comment by amijabd** [comment]
@will86 
Okay. Managed to figure it out. Thanks for the assist.

**Comment by priyankverma** [comment]
@amijabd I have exactly the same problem, how you fixed the problem?

**Comment by dongyuekai** [comment]
我这边遇到一个问题 加载china map的时候,在安卓上一切OK，在iOS上 模拟器正常，连线跑到真机上一切正常，release出ipa包后装到手机上就不显示了，最后找到了原因是因为html模板加载路径问题，解决办法如下:
1.在项目全局运行npm run bundle-ios
2.我把html中引用的加载js路径不正确的js文件直接拷贝到了html中，这样不存在路径问题了
经验证，iOS的release模式可以显示出来了

**Comment by SiroSong** [comment]
> 我这边遇到一个问题 加载china map的时候,在安卓上一切OK，在iOS上 模拟器正常，连线跑到真机上一切正常，release出ipa包后装到手机上就不显示了，最后找到了原因是因为html模板加载路径问题，解决办法如下:
> 1.在项目全局运行npm run bundle-ios
> 2.我把html中引用的加载js路径不正确的js文件直接拷贝到了html中，这样不存在路径问题了
> 经验证，iOS的release模式可以显示出来了

你这个中文是英语老师教的吧，，，，，第二条你自己读试试，能读懂吗？
