### ISSUE TITLE
打包之后图标不显示

### ISSUE THREAD

**Issue by maskTAQ** [somonus/react-native-echarts#14]
在测试的时候图表正常显示，可是打包之后就不显示了。
![h58_ pz0_ dq l k_p7t 2](https://cloud.githubusercontent.com/assets/19301145/21080652/70d06daa-bfef-11e6-9e16-43922cf2adde.png)
这是海马玩 模拟器。
真机上什么都不显示

**Comment by somonus** [comment]
same as #12

**Comment by taiaq** [comment]
谢谢大神。

**Comment by taiaq** [comment]
谢谢大神。

**Comment by chen236310** [comment]
same as

**Comment by chen236310** [comment]
html 文件放后台 uri 连接~，打包路径是错误的~

**Comment by kaola8246** [comment]
我打包完，安装后显示的图表是空白，但是测试是好的？不知道啥情况，大大知道怎么解决吗？

**Comment by xuchuang** [comment]
我也遇到了，真机测试还好，打包成release就不显示了，有大神解决一下吗？谢谢了

**Comment by challengerST** [comment]
> same as #12

没看懂
