### ISSUE TITLE
请问你们在运行的时候，每次渲染图形会不会闪烁？

### ISSUE THREAD

**Issue by kjjacket** [somonus/react-native-echarts#20]
我在app里用了这个插件画雷达图，底色是黑色的，打开界面的时候雷达图会闪一下（就是先整个区域都是白底，然后再出现生成好的雷达图）。每次界面上scrollview拖动的时候，也会闪一次。
请问你们生成图表的时候会不会有这种情况？

**Comment by jiaojunjiahanlin** [comment]
会的

**Comment by haoziy** [comment]
它的重绘机制有问题;只要有触发state他都reload了;自己改一下就好;
![image](https://cloud.githubusercontent.com/assets/12541846/23638220/3737c362-031b-11e7-9167-3dae394165eb.png)

**Comment by ZhouYongfan** [comment]
谢谢楼上，同时解决了真机测试断开包服务器会报警告的问题。

**Comment by kjjacket** [comment]
非常感谢。

**Comment by weiTimes** [comment]
请问在哪里解决这个重绘机制的问题，是修改该库还是修改调用该组件的页面？
