### ISSUE TITLE
Release版本怎么也显示不出图来（模拟器+真机）

### ISSUE THREAD

**Issue by jlapton** [somonus/react-native-echarts#34]
IOS,安卓没试，RN是0.41

试过{uri: 'web/xxx.html'}
甚至试过把js和injectJavascript的内容都拼到html里，然后用{html: 拼好的大字符串}
图表都出不来，但是debug就正常。折腾两天了:(

**Comment by jlapton** [comment]
反复排查，似乎跟 #24 是同一个问题，只要option中的属性带function就会在release版本中显示不出图表来，无论是ES6的()=>还是传统function的写法。但是对应的html如果存成文件后用电脑上的浏览器打开也是可以正常显示的，这个问题感觉好奇怪。

**Comment by jlapton** [comment]
修改了这2处，暂时解决了我的问题。。
https://github.com/jlapton/react-native-echarts/blob/master/src/util/toString.js
https://github.com/jlapton/react-native-echarts/blob/master/src/components/Echarts/index.js
但不知道有没有其他副作用，因此暂时没有pull request.

**Comment by hnsy2016** [comment]
感谢大神，参考你的方案解决了~

**Comment by hanFengSan** [comment]
你这改法是有副作用的....ios是好了, android是彻底怎么都不显示了😢

**Comment by hanFengSan** [comment]
只修改toString.js, android就没问题了.
