### ISSUE TITLE
Chart doesn't resize properly

### ISSUE THREAD

**Issue by superandrew213** [somonus/react-native-echarts#43]
For some reason my charts don't resize properly consistently. Sometimes they do, sometimes they don't. It's pretty random.

![simulator screen shot 15 may 2017 4 33 34 pm](https://cloud.githubusercontent.com/assets/13059204/26045311/ed9b7f48-398c-11e7-88f1-f12d6d041349.png)

Both charts have same number of data points but top chart doesn't fit all the data like the bottom chart. You can see that on top chart the bar on the right is cut off. It seems that the width must be bigger.

So far it's only happening for me if I have more than 1 chart.

These are my options:
```
const option = {
      title: { show: false },
      tooltip: {
        show: false,
        // formatter: `${unitOfMeasure ? `{c0} ${unitOfMeasure}<br />` : ''}{b0}`,
      },
      legend: { show: false },
      grid: {
        height: 130,
        top: 30,
        bottom: 0,
        borderWidth: 0,
        left: 15,
        right: 15,
      },
      xAxis: {
        type: 'category',
        data: data.xValues,
        // scale: true,
        boundaryGap: true,
        axisLine: {
          show: false,
          onZero: false,
        },
        axisTick: { show: false },
        axisLabel: {
          textStyle: StyleSheet.flatten(styles.axisLabel),
        },
        splitLine: { show: false },
        min: 'dataMin',
        max: 'dataMax',
      },
      yAxis: {
        scale: false,
        axisLine: {
          show: false,
          onZero: false,
        },
        axisTick: { show: false },
        axisLabel: { show: false },
        splitLine: { show: false },
      },
      dataZoom: [{
        type: 'inside',
        start: 50,
        end: 100,
      }],
      series: [{
        type: 'bar',
        data: data.yValues,
        color: ['#3897f0'],
      }],
    };
```

**Comment by superandrew213** [comment]
If I pass `width` as prop, it shrinks the outer container but the echart container still doesn't properly resize. Passing down `width` prop to echart container too solves this.

https://github.com/somonus/react-native-echarts/pull/44

So my charts are resizing properly as long as I give them a width.

**Comment by gaozhaopei** [comment]
@superandrew213  我的也是这种  传递了宽度属性之后好像 echarts外面的view 宽度起作用了  但是echarts的宽度还是不起作用

**Comment by superandrew213** [comment]
@gaozhaopei I'm not sure that I understand correctly. Translation is not good.

Try my fork https://github.com/superandrew213/react-native-charting.

You can install it with `npm i --save react-native-charting`

Make sure to set a width.

```
<Echarts
  height={200}
  width={window.width}
  option={option}
  onPress={onPress}
/>
```

**Comment by gaozhaopei** [comment]
<Echarts 
option={option2} 
height={277} 
width={WINDOW_WIDTH}/>


index.js
 <View style={{flex: 1, height: this.props.height || 400,width:this.props.width}}>
        <WebView
          ref="chart"
          scrollEnabled = {false}
          scalesPageToFit={false}
          injectedJavaScript = {renderChart(this.props)}
          style={{
            height: this.props.height || 400,
            width:this.props.width
          }}
          //source={require('./tpl.html')}
          source={{uri: 'file:///android_asset/tpl.html'}}
        />
      </View>


tpl.html 中有一个id 是#main 是这样设置的 #main {
        height: 100%;
      }
no width  不知道是不是和这个有关系 @superandrew213   谢谢您
