### ISSUE TITLE
背景透明问题，安卓打包后不显示问题，一键搞定

### ISSUE THREAD

**Issue by mqycn** [somonus/react-native-echarts#77]
下载地址：[https://github.com/mqycn/react-native-echarts-fix](https://github.com/mqycn/react-native-echarts-fix)

![](https://github.com/mqycn/react-native-echarts-fix/raw/master/help.png)

**Comment by only4ly** [comment]
mac怎么修复啊

**Comment by mqycn** [comment]
@only4ly 最新版本，作者已经修复白屏问题了。https://github.com/somonus/react-native-echarts/blob/master/src/components/Echarts/index.js，IOS开发，直接更新下 react-native-echarts 就可以了。Android开发，可以参考https://github.com/somonus/react-native-echarts/issues/12，手工复制tpl就可以了
