### ISSUE TITLE
debug模式下正常显示，但release下什么都不显示

### ISSUE THREAD

**Issue by liuchao1986105** [somonus/react-native-echarts#8]
gradle用的是1.3.1， 编译过程中遇到
android\app\src\main\res\drawable-mdpi\node_modules_nativeecharts_src_components_echarts_tpl.html: Error: The file name must end with .xml or .png的问题， 然后根据https://github.com/googlecreativelab/landmarker/issues/2将其move到res/raw目录下， 不知道是不是这个原因

**Comment by somonus** [comment]
这是老版react-native的bug，解决方案参考https://github.com/facebook/react-native/issues/6004
